### ISSUE TITLE
ISY integration failing to start

### ISSUE THREAD

**Issue by taz-man** [shbatm/hacs-isy994#112]
I'm running Home Assistant on eisy and I think HA starts faster then ISY which causes the ISY integration to report Failed to set up. If I Reload the ISY integration it starts up no problem. Michel from UDI has given me steps to get ISY and PG3 to load before HA but we were unable to get it to work. Could the ISY integration be setup to try and start again after a failure? It would be nice to get your thoughts on how this could be handled! Below is the error I get upon restart.
2024-03-19 16:34:05.826 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry IoX (10.0.1.66) for isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/isy994/__init__.py", line 112, in async_setup_entry
    await isy.initialize(
  File "/usr/local/lib/python3.12/site-packages/pyisyox/isy.py", line 128, in initialize
    await asyncio.gather(*isy_setup_tasks)
  File "/usr/local/lib/python3.12/site-packages/pyisyox/helpers/entity_platform.py", line 120, in update
    self.parse(xml_dict)
  File "/usr/local/lib/python3.12/site-packages/pyisyox/programs/__init__.py", line 64, in parse
    if not (features := xml_dict["programs"]["program"]):
                        ~~~~~~~~^^^^^^^^^^^^
KeyError: 'programs'

Thank you for your work.
Tom

**Comment by shbatm** [comment]
There's been some changes to the recent versions of Home Assistant in how it loads integrations and I haven't had time to replicate the changes from the Core integration back to this version yet--I suspect that is causing some of the race conditions.

As far are resetting the integration automatically, you could temporarily add an automation to reload the ISY entry after Home Assistant has been fully restarted:

```yaml
description: ""
mode: single
trigger:
  - platform: homeassistant
    event: start
    id: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: homeassistant.reload_config_entry
    target:
      device_id: 4c62a88de2ea41d2ad58625eecc493e2
    data: {}
```

Note: if you add this in the automation editor in Home Assistant, you can use "Choose Device" under Target for the service call to pick your Eisy (or any device linked to it) and it should reload the whole configuration.
