### ISSUE TITLE
HomeAssistant is not responsive to manual switch changes

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#35]
On the current release. 1.2.1
Two lights were turned on manually.
HomeAssistant did not change status.
Admin panel indicated status change.
Rebooted ISY and same result.

All devices are still capable of being controlled by HA.

**Comment by shbatm** [comment]
Please make sure you have debug logging turned on an post the logs from the time you switch the devices on.

```yaml
# Example configuration.yaml entry
logger:
  default: info
  logs:
    custom_components.isy994: debug
```
