### ISSUE TITLE
Unable to get Z-Wave devices to show up from ISY

### ISSUE THREAD

**Issue by bkvargyas** [shbatm/hacs-isy994#67]
At some point in time, I removed the HACS install of this plug in, since the code base was in .110.  However, when removing the HACS install and re-adding the integration, all my z-wave devices within the ISY99 no longer show up and are recognized (2 door locks and 1 light).

I've went back and installed 2.0b2 of this plug in just to see if anything has changed, and still no zwave devices.   Tried rebooting the ISY, HA system, uninstalling, re-installing, still nothing.   No errors on the ISY.   Last time I saw it working was just as I uninstalled V1.51 as V.110 of HA came out, and subsequent upgrades worked, until I removed the ISY99 integrated and tried to re-add...since then, never seen it since.

Ideas?

Brian

**Comment by shbatm** [comment]
Just out of curiosity, check your sensor and ignore strings to make sure they're not hiding anything by accident. From the Integrations page find the ISY and click Options to change them. That's the only obvious thing I can think of that would prevent only z-wave from showing up.

Next to that would be to enable debug logging and see if there's anything reported about ignoring entries.

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.isy994: debug
    custom_components.isy994: debug
    pyisy: debug
```
