### ISSUE TITLE
Lock Template

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#99]
Is there a way to be able to allow a template in either the user_num or code field?

```
service: isy994.set_zwave_lock_user_code
data:
  user_num: 3
  code: {{ states('number.s_casita_guest_code') | int }}
target:
  entity_id: lock.casita
```

**Comment by shbatm** [comment]
It should work in YAML mode, make sure you put double quotes around the whole template line or use this (block scalar) :

```yaml
value: |-
  {{ template here }}
```

**Comment by MechEng70** [comment]
Will try that today.  Thanks.

**Comment by MechEng70** [comment]
I tried this:
```
          action: call-service
          service: isy994.delete_zwave_lock_user_code
          data:
            user_num: '{{ states(''input_select.user_number_idooruser'') | int }}'
          target:
            entity_id: '{{ states(''input_select.locks'') | string }}'
```

In the template tab:
![image](https://user-images.githubusercontent.com/11697710/221369637-af3ce3ce-1866-4d0a-b24b-f3ef0d7db161.png)

![image](https://user-images.githubusercontent.com/11697710/221369655-ab6d4bac-cf7a-4150-b925-69d6e9c0916d.png)



REsulted in this error:

`2023-02-25 08:52:24.246 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139801490048624] Error handling message: Templates are not supported here. Got {'type': 'call_service', 'domain': 'isy994', 'service': 'delete_zwave_lock_user_code', 'target': {'entity_id': Template("{{ states('input_select.locks') | string }}")}, 'service_data': {'user_num': "{{ states('input_select.user_number_idooruser') | int }}"}, 'id': 91} (invalid_format) from 172.16.4.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) `

**Comment by shbatm** [comment]
Are you trying to do it from a dashboard card? You'll probably have to find a custom card that takes templates, like [button-card](https://github.com/custom-cards/button-card) or [config-template-card](https://github.com/iantrich/config-template-card).

Alternatively, use a [script](https://www.home-assistant.io/integrations/script/) and call the script from the button.

**Comment by MechEng70** [comment]
Yes.  Will do.  Thanks.

**Comment by MechEng70** [comment]
Scripts is the way.  Leaving this here is some needs to call a service (Script) from an entity card.

```
service: isy994.set_zwave_lock_user_code
data:
  user_num: "{{ states('input_select.user_number_idooruser') | int }}"
  code: "{{ states('input_text.door_code_idoorcode') | int }}"
target:
  entity_id: "{{ states('input_select.locks') | string }}"
```

```
service: isy994.delete_zwave_lock_user_code
data:
  user_num: "{{ states('input_select.user_number_idooruser') | int }}"
target:
  entity_id: "{{ states('input_select.locks') | string }}"
```
